clc
clear all
uiopen
mul = 1;
 run UKF_Complete_dataGen.m;
 run EKF_Complete_dataGen.m;
 run IEKF_Complete_dataGen.m;
 run AIEKF_Complete_dataGen.m;
 run PF_Complete_dataGen.m;

save('moduleEstimation_DataSetName','true', 'modules','ues');
clear all
load('moduleEstimation_DataSetName');
%% -------------------------- Elapsed Time -------------------------------

elapsedTime.ekf.cumulative = ...
    [modules.ekf.elapsedTime.Myf, modules.ekf.elapsedTime.Myr,...
     modules.ekf.elapsedTime.Vy, modules.ekf.elapsedTime.YawR,...
     modules.ekf.elapsedTime.Beta, ues.noKF.ekf.elapsedTime,...
     ues.KF.ekf.simTime];
 
 elapsedTime.iekf.cumulative = ...
    [modules.iekf.elapsedTime.Myf, modules.iekf.elapsedTime.Myr,...
     modules.iekf.elapsedTime.Vy, modules.iekf.elapsedTime.YawR,...
     modules.iekf.elapsedTime.Beta, ues.noKF.iekf.elapsedTime,...
     ues.KF.iekf.simTime];
 
 elapsedTime.aiekf.cumulative = ...
    [modules.aiekf.elapsedTime.Myf, modules.aiekf.elapsedTime.Myr,...
     modules.aiekf.elapsedTime.Vy, modules.aiekf.elapsedTime.YawR,...
     modules.aiekf.elapsedTime.Beta, ues.noKF.aiekf.elapsedTime,...
     ues.KF.aiekf.simTime];
 
 elapsedTime.ukf.cumulative = ...
    [modules.ukf.elapsedTime.Myf, modules.ukf.elapsedTime.Myr,...
     modules.ukf.elapsedTime.Vy, modules.ukf.elapsedTime.YawR,...
     modules.ukf.elapsedTime.Beta, ues.noKF.ukf.elapsedTime,...
     ues.KF.ukf.simTime];
 
 elapsedTime.pf.cumulative = ...
    [modules.pf.elapsedTime.Myf, modules.pf.elapsedTime.Myr,...
     modules.pf.elapsedTime.Vy, modules.pf.elapsedTime.YawR,...
     modules.pf.elapsedTime.Beta, ues.KF.pf.simTime];