function Jacobian = jacobianState(T,Vx,const)
%JACOBIANSTATE2
%    JACOBIAN = JACOBIANSTATE2(T,VX,C1,C2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    08-Oct-2018 17:09:56

g=const(1);
Iz=const(2);
lf=const(3);
lr=const(4);
m=const(5);
l=lf+lr;

c1=m*lr/l;
c2=Iz/l;


Jacobian = reshape([1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,T.*c1,T.*c2,-T.*Vx,1.0,-T,0.0,0.0,0.0,0.0,1.0],[5, 5]);
