function Jacobian = jacobianMeas(Vx)
%JACOBIANMEAS2
%    JACOBIAN = JACOBIANMEAS2(VX)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    09-Oct-2018 00:26:27

Jacobian = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Vx,0.0,0.0,0.0,0.0,0.0,0.0,Vx],[5, 5]);
